Repository johnsonandjohnson/njmm, pull requests merged in 2020-12, with the labels that each got.

#6 Bugfix/deploy script
  .github/workflows/njmmbuild.workflow.yml
  .github/workflows/njmmdeploy.workflow.yml
  DESCRIPTION
  app_utils/census_utils.R
  app_utils/color_utils.R
  app_utils/label_utils.R
  app_utils/leaflet_utils.R
  app_utils/methodology_utils.R
  app_utils/plotly_utils.R
  global.R
  renv.lock
  renv/.gitignore
  renv/activate.R
Labels: bug

#11 removing shinylogs and all dependencies
  global.R
  renv.lock
  server.R
Labels: enhancement

#14 Adding back required packages
  renv.lock
Labels: bug

#16 Update README.md
  README.md
Labels: documentation

#19 Readme updates
  README.md
Labels: documentation
